site_name: Entity Construction Kit
site_description: Provides the ability to create and manage custom CiviCRM entities.
site_author: SYSTOPIA GmbH
repo_url: https://github.com/systopia/de.systopia.eck

theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Entities': entities.md
  - 'Configuration': configuration.md
  - 'Usage': usage.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
